### ISSUE TITLE
build/binstar/public queue does not support svn

### ISSUE THREAD

**Issue by emka** [Anaconda-Server/anaconda-build#101]
I submitted a build from subversion source with ```meta.yaml``` containing

```yaml
source:
  svn_url: http://...
```
 to the ```build/binstar/public``` queue.

The build fails because there is no ```svn``` in the docker image:
```Error: svn is not installed```

Could you please add svn to the default image?

**Comment by PeterDSteinberg** [comment]
@srossross I have addressed this issue as follows:
 * [New docs.anaconda.org PR](https://github.com/Anaconda-Server/docs.anaconda.org/pull/235) that says subversion must be installed
 * Updated our internal wiki on build worker deployment instructions for the various operating systems to say subversion must be installed
 * Created a PR on the [anaconda-builder cluster plugin repo](https://github.com/ContinuumIO/anaconda-cluster-contrib/pull/14) . That PR adds subversion to the requirements of the worker initialization.  I'm not sure how to test this anaconda-cluster-plugin PR, if you have any suggestions.

**Comment by PeterDSteinberg** [comment]
@srossross I think this is ready for review.  I have personally tested the modification to the anaconda-build-worker plugin.

**Comment by srossross** [comment]
@PeterDSteinberg This also needs to get built into the [public docker image](https://github.com/Anaconda-Server/anaconda-build/blob/develop/docker/linux-64/Dockerfile)

**Comment by PeterDSteinberg** [comment]
This has also been updated in the [docker image code here](https://github.com/Anaconda-Server/anaconda-build/blob/develop/docker/linux-64/Dockerfile#L5) and the docker image has been push with the following tags:
 * `binstar/linux-64:latest`
 * `binstar/linux-64:0.14.0`

The cluster plugin PR has been merged and the docs PR has been merged.

Closing.
