### ISSUE TITLE
Worker registration info as json at command line interface

### ISSUE THREAD

**Issue by PeterDSteinberg** [Anaconda-Server/anaconda-build#123]
For 
```
anaconda worker register|list|deregister
```
provide an --json flag to let the output be a single json for machine reading.

**Comment by stephenakearns** [comment]
@PeterDSteinberg please move to in progress or ready for review pipeline if appropriate

**Comment by PeterDSteinberg** [comment]
I'm closing this issue.  We decided a json handler was too much an overhaul in several layers of code.
