### ISSUE TITLE
Retest su_worker after conda 1751 and 1752 issues are fixed.

### ISSUE THREAD

**Issue by PeterDSteinberg** [Anaconda-Server/anaconda-build#126]
The su worker branch is ready to merge, except for the fact that there were bugs in 

```
conda clean -pt
```

After conda issues 1751 and 1752 are resolved, then retest su worker with an updated conda and merge the su worker branch into develop.

**Comment by PeterDSteinberg** [comment]
And also merge this documentation PR at the same time as the su worker branch merge:

https://github.com/Anaconda-Server/docs.anaconda.org/pull/162

**Comment by PeterDSteinberg** [comment]
@stephenakearns the conda issues 1751 and 1752 that were holding up ```su_worker``` have been merged.  Should I revisit this ```su_worker``` code now?

**Comment by stephenakearns** [comment]
@PeterDSteinberg yes - please, sorry just saw this comment today.

**Comment by PeterDSteinberg** [comment]
This contents of this issue have been accomplished in #88 's testing. We should close  this issue when that PR #88 is finalized and merged.

**Comment by stephenakearns** [comment]
closing this as the work is now represented in #88
