### ISSUE TITLE
Build: understand what Cluster team needs to get them up and running with Build

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Server/anaconda-build#127]

**Comment by stephenakearns** [comment]
Hi @damianavila I think from our sprint planning, you were going to look at this.

**Comment by stephenakearns** [comment]
Sorry @damianavila  - my mistake - this one was correctly assigned to Marcos - fixed that.

**Comment by damianavila** [comment]
>Sorry @damianavila - my mistake - this one was correctly assigned to Marcos - fixed that.

No problem :wink:

**Comment by malev** [comment]
@stephenakearns I talked with ben, they are open to start using AB. But we have to do 2 things in order to have that running:
* deploy AB 0.13.1 in linux-64, win and osx
* fix #572

There is a discussion about that [here](https://www.flowdock.com/app/continuum/anacondaserver/threads/tSBcvpTJ8TIrduI8X_NaphY7FDT)

**Comment by stephenakearns** [comment]
thanks @malev - for point 1, can you clarify - are you referring to the release of AB 0.13.1 (that's happened and its available to install). I'm guessing you're referring to setting up workers using 0.13.1. If so, then I think that @srossross  may be setting these up on Monday

Re: point 2 - I see that Mike Marchetti posted a workaround - does that solve Ben's problem or does he still need a fix. Any sense of how difficult 572 will be based on how it's presenting? (I know with bugs its impossible to estimate sometimes)

**Comment by stephenakearns** [comment]
done - create new issue in next srpint to support cluster
