### ISSUE TITLE
Better name for environment variables in Anaconda Build Recipe

### ISSUE THREAD

**Issue by goanpeca** [Anaconda-Server/anaconda-build#135]
From @amccarty: 
>### env
An export of environment variables for the sub-build
```yaml
env:
  - FOO=BAR
  - ANACONDA=GREAT JENKINS=OK
```

>Maybe we should use a different name? envvars? First few times I read this I wasn't sure if we were specifying conda envs to use or if this would be creating new envs. In reality it's neither.

**Comment by PeterDSteinberg** [comment]
I agree ```envvars``` is a better name.  I'll make the change if I get a +1.

**Comment by goanpeca** [comment]
Hi @PeterDSteinberg you have a :+1: from my side :p,

@srossross ?

**Comment by srossross** [comment]
:+1: but it needs to be backwards compatible.

**Comment by PeterDSteinberg** [comment]
Don't review this quite yet - I realized I should make it work with the PR of anaconda-server #1451, _as_ _well_ _as_ _with_ an anaconda-server that has not been updated.  Otherwise we'll have backwards compatibility issues between server and build.

**Comment by stephenakearns** [comment]
Note - will have dependency on an updated version of Anaconda Repository (aka server) that contains the release of the PR above
