### ISSUE TITLE
Build: Resolve Cluster build issues

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Server/anaconda-build#136]
Dependencies: 
* [x] conda clean issue 1751 - conda/conda#1751
* [x] fix Anaconda-Server/anaconda-server#572 (derek - review)
* [x] deploy AB 0.13.1 in linux-64, win and osx (Sean: ramp up Kamill/Troy)

Success Criteria
* [ ] Loop back with @quasiben to confirm working build for cluster

**Comment by rafaelhbarros** [comment]
Waiting for conda merges

**Comment by rafaelhbarros** [comment]
@stephenakearns Issue 1751 fixed in a merge. Now should I wait for the deploy or nudge someone?

**Comment by stephenakearns** [comment]
See 1751 - @srossross has asked for patch release of conda (A dev build is not a recommended approach)

**Comment by srossross** [comment]
@ilanschnell when is the next patch release of conda planned?

**Comment by ilanschnell** [comment]
Conda 3.18.6 was released yesterday, and it includes https://github.com/conda/conda/pull/1807

**Comment by rafaelhbarros** [comment]
thanks @ilanschnell

**Comment by srossross** [comment]
:trophy:

**Comment by stephenakearns** [comment]
@srossross - I think you're working on this one - assigning over to you.

**Comment by stephenakearns** [comment]
Hi @rafaelhbarros - now that the build system is working again with Mac and Windows, are we able to complete the work on this one? If yes, let's include it in next sprint - thoughts?

**Comment by rafaelhbarros** [comment]
@stephenakearns: well, I don't know what is needed to be done one the cluster, but they can go ahead and see if their issue is solved.

So, please, let's include some work on the next sprint but I'll need some guidance if I need to do anything.

**Comment by ContinuumJira** [comment]
I think Derek's been active on this -can you sync up with him?

On Mon, Dec 7, 2015 at 9:42 AM, Rafael Hoffmann de Barros <
notifications@github.com> wrote:

> @stephenakearns <https://github.com/stephenakearns>: well, I don't know
> what is needed to be done one the cluster, but they can go ahead and see if
> their issue is solved.
>
> So, please, let's include some work on the next sprint but I'll need some
> guidance if I need to do anything.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Anaconda-Server/anaconda-build/issues/136#issuecomment-162562058>
> .
>



-- 
*Stephen Kearns*
*Product Manager*

*w: (512) 776-1096*
*m: (737) 444-0474*
*t: @stephenakearns*
*skype: stephen.kearns*

**Comment by stephenakearns** [comment]
Hi @quasiben - looking at the build results on Anaconda-Cloud for the Cluster team here: https://anaconda.org/anaconda-cluster/anaconda-cluster/builds

It seems like you are only building for Linux-64 and Mac-64. I was curious to know if you were ready to re-enable Win-64 (and other supported platforms) to see if they are building smoothly for you now? If yes, could you give that a shot and report results back here?

**Comment by quasiben** [comment]
Things are now working on all three platforms for Anaconda Cluster builds:
https://anaconda.org/anaconda-cluster/anaconda-cluster/builds/1397

**Comment by PeterDSteinberg** [comment]
I'm closing this issue.  Let me know if you have any build issues @quasiben
