### ISSUE TITLE
Packages configured to be uploaded aren't

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Server/anaconda-build#141]
Take a gander at https://anaconda.org/ijstokes/serpent/settings/ci?edit=1 and you'll notice that all `master` commits should be uploaded.  Then take a look at https://anaconda.org/ijstokes/serpent/builds and notice how build 4.5-9 (which all built successfully) weren't uploaded.

**Comment by srossross** [comment]
@ijstokes I don't have access to https://anaconda.org/ijstokes/serpent/settings/ci?edit=1 can you post a screen shot?

**Comment by ijstokes** [comment]
@srossross I've added you as a collaborator on the package, but here are screenshots anyway (and for the sake of others who might try to either explain what I've done wrong, or figure out if this is a bug)

<img width="608" alt="screen shot 2015-11-14 at 10 52 41 pm" src="https://cloud.githubusercontent.com/assets/293525/11167117/77c9057a-8b22-11e5-8e87-2ed5f21d71bb.png">

<img width="419" alt="screen shot 2015-11-14 at 10 53 16 pm" src="https://cloud.githubusercontent.com/assets/293525/11167120/867de752-8b22-11e5-812d-552b8096d39f.png">

<img width="726" alt="screen shot 2015-11-14 at 10 54 08 pm" src="https://cloud.githubusercontent.com/assets/293525/11167126/a92bd570-8b22-11e5-956e-655f4cf5eb39.png">

**Comment by srossross** [comment]
@ijstokes you need to do the same as the test branch where you do `refs/heads/.*`, add  `refs/heads/master`  not `master`
