### ISSUE TITLE
Feature request: build alerts

### ISSUE THREAD

**Issue by rafaelhbarros** [Anaconda-Server/anaconda-build#149]
I would like to get completion warnings on the builds that were triggered by my pull requests.

Once I submit a PR I want the finished builds to send me an email, text or smoke signal saying the status of the finished build.

Bonus points if the relevant piece of the log is on the email somehow.

**Comment by goanpeca** [comment]
:+1:

**Comment by stephenakearns** [comment]
:+1:

**Comment by PeterDSteinberg** [comment]
@rafaelhbarros I'm not clear whether this feature has already been implemented?  I get notifications from ```noreply@anaconda.org via amazonses.com ``` regarding my pushes to [https://github.com/PeterDSteinberg/myorg.package1](https://github.com/PeterDSteinberg/myorg.package1) which has a CI trigger and local build worker.   The email describes build status for each part of the build matrix.

**Comment by rafaelhbarros** [comment]
@PeterDSteinberg I wanted something to message me when the build is done, and I don't get any email currently. When should that happen? How do I make it happen?

**Comment by PeterDSteinberg** [comment]
@rafaelhbarros I have a package myorg.package1 for which I set up CI builds on any branch push.  I set it up in this UI page: 

https://anaconda.org/psteinberg/myorg.package1/settings/ci?edit=1

At the bottom of that edit page, there is a space to enter comma-separated emails who should be notified.  I added my continuum.io email there when I set up the CI builds on myorg.package1 and I have been getting emails related to builds on any push.  The emails look like:

```
Anaconda Cloud Build noreply@anaconda.org via amazonses.com 
7:31 PM (13 hours ago)

to me 
Build psteinberg/myorg.package1 #9 Errored

Repo:

Github Repo
PeterDSteinberg/myorg.package1
Branch
fix/better_conda
Commit
7e5d4ec9
Diff
6bed22ff...7e5d4ec9
Build Items:

9.0 error | [ platform="osx-64" engine="python=2.7" env="None" ]
9.1 error | [ platform="osx-64" engine="python=3.4" env="None" ]
9.2 error | [ platform="osx-64" engine="python=3.5" env="None" ]
```

**Comment by rafaelhbarros** [comment]
that looks good, can be closed.
