### ISSUE TITLE
setting some env variables based on numpy in 'engine'

### ISSUE THREAD

**Issue by PeterDSteinberg** [Anaconda-Server/anaconda-build#151]
Sui mentioned this issue in flowdock.  His quote is below.  The idea is that we should detect numpy being part of the 'engine' in .binstar.yml and then set CONDA_NPY env variable automatically based on that.

I have a binstar.yml with:
engine:
    - python=2.7 numpy=1.9
    - python=2.7 numpy=1.10
    - python=3.4 numpy=1.10
    - python=3.4 numpy=1.9
It seems that anconda build does not set CONDA_NPY
and the new conda build numpy x.x requires numpy version to be set
so I have to do:
conda buildpython env_helper.py-c numba buildscripts/condarecipe.local --no-test 9:09
(I can’t get it to format right)
but the point is that I have to use a script to set the right —python=x.x and —numpy=x.x
from BINSTAR_ENGINE 9:10
Is there a better way?

**Comment by ContinuumJira** [comment]
Hi Peter,
can you help me understand the impact of solving this problem a bit better:
(a) Bug or enhancement (reading the description it looks like something
changed in conda build which created this issue)
(b) Workaround exists? (seems like the answer is yes)
(c) time/effort for workaround?
(d) number of users who would use or benefit from this?

On Tue, Dec 8, 2015 at 4:01 PM, Peter Steinberg <notifications@github.com>
wrote:

> Sui mentioned this issue in flowdock. His quote is below. The idea is that
> we should detect numpy being part of the 'engine' in .binstar.yml and then
> set CONDA_NPY env variable automatically based on that.
>
> I have a binstar.yml with:
> engine:
> - python=2.7 numpy=1.9
> - python=2.7 numpy=1.10
> - python=3.4 numpy=1.10
> - python=3.4 numpy=1.9
> It seems that anconda build does not set CONDA_NPY
> and the new conda build numpy x.x requires numpy version to be set
> so I have to do:
> conda buildpython env_helper.py-c numba buildscripts/condarecipe.local
> --no-test 9:09
> (I can’t get it to format right)
> but the point is that I have to use a script to set the right —python=x.x
> and —numpy=x.x
> from BINSTAR_ENGINE 9:10
> Is there a better way?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Anaconda-Server/anaconda-build/issues/151>.
>



-- 
*Stephen Kearns*
*Product Manager*

*w: (512) 776-1096*
*m: (737) 444-0474*
*t: @stephenakearns*
*skype: stephen.kearns*

**Comment by goanpeca** [comment]
@stephenakearns is that you as jira again?

**Comment by PeterDSteinberg** [comment]
The workaround is cumbersome even for internal Continuum users.  I imagine outside users would not figure out the workaround.  The level of effort to fix it is a half day or less.  I would call it a bug fix.

**Comment by PeterDSteinberg** [comment]
Closing because #147 merged.
