### ISSUE TITLE
Build packages aren't uploaded even when branch is configured for upload

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Server/anaconda-build#152]
Commits to `master` should be flagged as `upload package` but they aren't.

https://anaconda.org/Anaconda-Notebook/hello-world/settings/ci

### Configuration

![screenshot 2015-12-10 06 54 46](https://cloud.githubusercontent.com/assets/293525/11714821/f1757b5a-9f0a-11e5-98e3-0aa3219a822d.png)

### Build Queue

![screenshot 2015-12-10 06 54 14](https://cloud.githubusercontent.com/assets/293525/11714834/09b477ca-9f0b-11e5-98d4-c577e1399c2d.png)

**Comment by dsludwig** [comment]
@ijstokes if you change `master` to `refs/heads/master`, the package is uploaded. I assume the regular expression matches the ref instead of the branch name is so that you could choose to have other refs uploaded by default, such as every tagged commit: `refs/tags/.*`.
