### ISSUE TITLE
Local .workers file can get out-of-sync

### ISSUE THREAD

**Issue by sklam** [Anaconda-Server/anaconda-build#154]
Local .workers files can get out-of-sync when user deregister workers from the web interface.  Do we really need to have that file on locally?

**Comment by stephenakearns** [comment]
@srossross or @dsludwig could you share your thoughts on this question?

**Comment by stephenakearns** [comment]
Adding @PeterDSteinberg to the thread - any thoughts Peter?

**Comment by PeterDSteinberg** [comment]
I am working on a fix for this here in PR #165 . Sorry forgot to reference the original issue.

**Comment by stephenakearns** [comment]
spoke with @PeterDSteinberg - this has been validated so we're closing. @sklam can you retry and if not resolved, can you comment and/or reopen?
