### ISSUE TITLE
Provide option to remove package install progress bars

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Server/anaconda-build#157]
I **think** this is due to some part of Anaconda Build mechanics: my build logs are filled with progress bars that obstruct my ability to see what is actually going on with the package build.  Can these be turned off?  Or is this only a function of my conda recipe?

**Comment by PeterDSteinberg** [comment]
@stephenakearns This issue was completed without assigning story points (merged yesterday).  It is 1 story point.

**Comment by PeterDSteinberg** [comment]
This was fixed by #160.
