### ISSUE TITLE
Bug: CI Builds not being triggered on specific branch

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Server/anaconda-build#166]
## Logged by 
@kwmsmith on the data portal projects

## Pre-requisite 
to work on this issue: have me (steve) or @kwmsmith add you as an owner to the Data-portal organization in A-Cloud 

## Description
- This branch ("remove-node-dist-files") is not triggering CI builds: https://github.com/ContinuumIO/dataportal/pull/122
- If you go to the builds page, you can see other branches being automatically built
https://anaconda.org/data-portal/dataportal/builds
- link to Data Portal's binstar.yaml: https://github.com/ContinuumIO/dataportal/blob/master/.binstar.yml

**Comment by stephenakearns** [comment]
@dsludwig - by any chance would your fix in #164 help resolve this issue?

**Comment by kwmsmith** [comment]
@srossross let me know if you need other screenshots.

![Screen Shot 2016-01-04 at 10.23.28 AM.png](https://files.zenhub.io/568a9ca89706f372552d517a)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by kwmsmith** [comment]
@srossross let me know if you need other screenshots.

<img width="1020" alt="screen shot 2016-01-04 at 10 23 28 am" src="https://cloud.githubusercontent.com/assets/288771/12094297/708eb8cc-b2cd-11e5-89b3-fed533533635.png">

**Comment by dsludwig** [comment]
@kwmsmith can you take a screenshot of https://github.com/ContinuumIO/dataportal/settings/hooks as well?

**Comment by dsludwig** [comment]
The fix in #164 only changes the label the artifacts would be uploaded to, it doesn't affect which branches are built.

**Comment by PeterDSteinberg** [comment]
@kwmsmith can you invite me to the dataportal project on anaconda.org.  I'm working on this issue.  I haven't been able to replicate it with a local worker listening for CI builds on any branch of my repo.  I'm curious to look at the metadata of the github push notification events and webhooks.  Also, if you push a trivial change to that ```remove-node-dist-files``` branch now, does that trigger a build (I'm wondering if the problem was some unknown build queue state issue that was transient at the time)?

**Comment by srossross** [comment]
@kwmsmith we are blocked on this until we get more information.

**Comment by dsludwig** [comment]
This may relate to the size of the PR: 200k lines removed, 18k files deleted.

**Comment by stephenakearns** [comment]
@kwmsmith closing this for now, but please reopen if issue persists.
