### ISSUE TITLE
Bug: can't `conda install -c some-channel dataportal`

### ISSUE THREAD

**Issue by kwmsmith** [Anaconda-Server/anaconda-build#168]
The [DataPortal organization on Anaconda Build](https://anaconda.org/data-portal) has two packages:

* [dataportal](https://anaconda.org/data-portal/dataportal) and
* [lux](https://anaconda.org/data-portal/lux).

The `dataportal` package has been [successfully built and uploaded to Anaconda Build](https://anaconda.org/data-portal/dataportal/builds/61).

I'm trying to take it all the way home, but I can't get `$ conda install -c some-channel dataportal` to work.

My first attempt was to use the [suggested command](https://conda.anaconda.org/data-portal/channel/dev):

```
$ conda install -c https://conda.anaconda.org/data-portal/channel/dev dataportal
Fetching package metadata: ......
Error: No packages found in current osx-64 channels matching: dataportal

You can search for this package on anaconda.org with

    anaconda search -t conda dataportal
```

I also tried:

```
$ TOKEN=$(anaconda auth --create --name conda-download-token)

$conda install -c https://conda.anaconda.org/t/%24TOKEN/data-portal/channel/dev dataportal
```

Which gave me a similar error message after authenticating.

**Update**: It looks like there's an error with the `conda install` commandline; after replacing `%24TOKEN` with `$TOKEN`, I *am* able to get `conda install` to work, here's what I did:

```
$ TOKEN=$(anaconda auth --create --name conda-download-token)

$ conda install -c https://conda.anaconda.org/t/$TOKEN/data-portal/channel/dev dataportal
Fetching package metadata: ......
Solving package specifications: ...............................................
Package plan for installation in environment /Users/ksmith/anaconda/envs/dataportal:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    dataportal-0.0.1           |                0         2.2 MB

The following NEW packages will be INSTALLED:

    dataportal: 0.0.1-0
[...]
```

So, I'd suggest correcting the commandline instructions.

Also, is there a cleaner way to do this `conda install` process for a private package like dataportal?

ping @ltransom @postelrich

**Comment by stephenakearns** [comment]
@kwmsmith - fix deployed to production today - can you validate and close this issue?

**Comment by stephenakearns** [comment]
Hi @kwmsmith pinging again - can you validate this is no longer an issue and close?

**Comment by stephenakearns** [comment]
Hi @kwmsmith (cc: @ltransom ) closing this issue, but happy to reopen if the issue re-appears.
