### ISSUE TITLE
"anaconda build" does not work on Mac OS X with anaconda-client v1.2.1

### ISSUE THREAD

**Issue by talumbau** [Anaconda-Server/anaconda-build#173]
I attempted to set up having my packages built using Anaconda Cloud. I was referred to the documentation here:

http://docs.anaconda.org/build.html

I attempted to follow these instructions but did not get very far because `build` is not a valid command for the anaconda-client:

```
(heroku_aei)0054-tjalumbaugh:conda.recipe talumbau$ conda update anaconda-client
Fetching package metadata: ........
# All requested packages already installed.
# packages in environment at /Users/talumbau/miniconda3/envs/heroku_aei:
#
anaconda-client           1.2.1                    py27_0
(heroku_aei)0054-tjalumbaugh:conda.recipe talumbau$ anaconda build init
usage: anaconda [-h] [--show-traceback] [--hide-traceback] [-v] [-q] [--color]
                [--no-color] [-V] [-t TOKEN] [-s SITE]
                ...
anaconda: error: argument : invalid choice: 'build' (choose from 'auth', u'channel', 'config', u'copy', u'download', 'groups', u'login', 'logout', u'notebook', 'package', 'remove', 'search', 'show', u'upload', u'whoami')
```

So, just wondering:

 - is the documentation wrong?
 - is the client broken?

Also, what is the proper way to set up automatic package build on Anaconda Cloud?

**Comment by PeterDSteinberg** [comment]
@talumbau Looks like you have an anaconda-client that is up-to-date but you did not ```conda install anaconda-build```.  The commands beginning with ```anaconda build``` or  ```anaconda worker``` come from anaconda-build.

**Comment by talumbau** [comment]
Ah. User error. I guess I actually have to read every instruction correctly and do what it says. Thanks @PeterDSteinberg. Closing.

**Comment by talumbau** [comment]
Hmmm. reopening...

```
0054-tjalumbaugh:conda.recipe talumbau$ conda install conda-build anaconda-client anaconda-build
Fetching package metadata: ........
Solving package specifications: .........................................
# All requested packages already installed.
# packages in environment at /Users/talumbau/miniconda3:
#
anaconda-build            0.10.7                   py33_0
anaconda-client           1.0.1                    py33_0
conda-build               1.18.2                   py33_0
0054-tjalumbaugh:conda.recipe talumbau$
0054-tjalumbaugh:conda.recipe talumbau$ anaconda build init
usage: anaconda [-h] [--show-traceback] [--hide-traceback] [-v] [-q] [--color]
                [--no-color] [-V] [-t TOKEN] [-s SITE]
                ...
anaconda: error: argument : invalid choice: 'build' (choose from 'auth', 'channel', 'config', 'copy', 'groups', 'login', 'logout', 'notebook', 'package', 'register', 'remove', 'search', 'show', 'upload', 'whoami')
```

**Comment by PeterDSteinberg** [comment]
@talumbau do a ```conda update anaconda-build```.  Your version of ```anaconda-build``` is old enough to be before the name change to ```anaconda``` from ```binstar build``` and hence you don't have ```anaconda build``` or ```anaconda worker``` now.

**Comment by talumbau** [comment]
Sadly this is the most recent version available for Python 3.3, which is the python version for my now ancient version of miniconda3. It sounds like the answer is for me to install a newer version of miniconda3 so that my root environment has a newer Python 3 version.

**Comment by PeterDSteinberg** [comment]
Sounds good. Currently it is build for Python 2.7, 3.4, 3.5

**Comment by PeterDSteinberg** [comment]
closing this as a conda/miniconda convenience issue
