### ISSUE TITLE
Zombie files cause builds to not include explicit dependencies

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Server/anaconda-build#176]
This may or may not be reproducible - capturing the issue for us to look at. Reported by the data portal team. 

---------- Forwarded message ----------
From: Lance Ransom <lransom@continuum.io>
Date: Thu, Jan 14, 2016 at 10:39 AM
Subject: Zombie Files on anaconda.org
To: Stephen Kearns <skearns@continuum.io>, Sean Ross-Ross <sean.ross-ross@continuum.io>, Michael Marchetti <michael.marchetti@anaconda.org>
Cc: Richard Postelnik <rpostelnik@continuum.io>, Kurt Smith <ksmith@continuum.io>

First and foremost, we are no longer blocked on this issue.

As I mentioned, I cannot attest to the exact sequence that lead to the problem, but it resembles this following:

*  Created a package that was independent of python version
*  Build file appeared as “os-64/dataportal/-0.0.1-0.tar.bz2” on anaconda.org
*  We pinned our package to python 3.4
*  New builds appear as “os-64/dataportal/-0.0.1-py34_0.tar.bz2” on anaconda.org
*  Builds consistently updated the new file, but the original file is still there
*  Conda install ALWAYS selected the original file:  “os-64/dataportal/-0.0.1-0.tar.bz2” (which was obsolete)
*  Removed the “zombie” files and everything is fine

Just FYI.

Thanks,
Lance

**Comment by srossross** [comment]
This seems like a conda issue at first glance. 

cc @ilanschnell or @kalefranz

**Comment by PeterDSteinberg** [comment]
closing this issue because the zombies were observed in build workers that had not been updated with the new process groups approach reflected in PR #158
