### ISSUE TITLE
su worker: make all / most tests use patch decorators

### ISSUE THREAD

**Issue by PeterDSteinberg** [Anaconda-Server/anaconda-build#182]
Currently the test_su_worker.py test has a few things to fix:
 * Nested `with patch(...` statements should be using patch decorators instead of `with` statements
 * More of the tests should be runnable by using mock / patch without requiring the test runner to be a valid su worker at test time.  (Currently most of the tests are skipped in most conditions).

**Comment by stephenakearns** [comment]
Hi @PeterDSteinberg - is suspect this is in progress - moved it to that pipeline. Could you update pipeline from the boards view if not the case? 

https://github.com/Anaconda-Server/anaconda-server#boards?repos=9108541,19550310,9064487,15382297,9266356,46084531&showClosed=false&showPRs=false

**Comment by PeterDSteinberg** [comment]
@StephenK This issue is fixed by to-be-reviwed-and-merged PR #88 , the later commits in that PR, where the tests are converted to using mock and patch for all but one test.  The work was best done before merging PR 88, so there isn't a PR directly for this issue.

**Comment by PeterDSteinberg** [comment]
Closing because running as root for su worker causes too much sales friction.
