### ISSUE TITLE
osx-64 times out on npm intall

### ISSUE THREAD

**Issue by johneo** [Anaconda-Server/anaconda-build#190]
The same build that passes on linux-64 fails on osx-64 during `npm install` due to timeout. `iotimeout` was set to 300 but still fails.

**Comment by PeterDSteinberg** [comment]
@johneo Can you provide a quote here of the full build log up to the hanging point?

**Comment by johneo** [comment]
[data-portal-osx64-buildfailurelog.txt](https://files.zenhub.io/56afd1a7f63f5a8a10c6c973)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by johneo** [comment]
Wondering if it is indeed waiting for a user input regarding X-Code CLI tools: https://github.com/nodejs/node-gyp/issues/773

**Comment by PeterDSteinberg** [comment]
@johneo This built successfully for me on mac osx locally.  I think you are right about the nodejs/node-gyp#773 issue you shared (that it is waiting for user input on X Code CLI tools).

**Comment by PeterDSteinberg** [comment]
@johneo Are you still blocked on this issue?  We have updated the build workers and I'm wondering if this problem still exists.

**Comment by johneo** [comment]
In short, no, not blocke anymore.

I was able to resolve it by doing `npm install --loglevel info` and increasing the iotimeout to 600. The builds on osx-64 take about 33 minutes, though, whereas the equivalent build on linux-64 takes 12 minutes or so.
