### ISSUE TITLE
[Build] Update build worker documentation and deploy updated build workers on A-Cloud

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Server/anaconda-build#192]
* [x] prereq: latest version of Anaconda Repository deployed 
* [x] involve Troy since he has the most experience here
* [x] decision: patch or rebuild workers? [Edit 
* [x] update documentation: current deploy/build docs here: https://sites.google.com/a/continuum.io/wiki/design-and-development-documents/binstar
* [x] make sure latest conda build release is installed/updated
* [x] build/update workers as needed: 
   * [x] public (lin-64 only)
   * [x] binstar/Continuum (all 5 types - check if there may be multiple worker instances)

**Comment by PeterDSteinberg** [comment]
All items checked off - see also #205
