### ISSUE TITLE
Spaces prepended to Description field

### ISSUE THREAD

**Issue by groutr** [Anaconda-Server/anaconda-build#195]
When editing the description for a package on my anaconda.org account, every time I edit the description, 4 spaces are prepended to the first line.

**Comment by PeterDSteinberg** [comment]
@groutr This is an anaconda-server issue.  Can you give the URL you are using when you edit your package description and have this trouble.  Then I'll create an issue in that repo and mention you.

**Comment by groutr** [comment]
It is not just one package, it's all of them.  I suspect this is a general problem.
The problem has actually compounded since I've filed this issue.  Now, instead of 4 spaces, there are 15 spaces prepended whenever an edit is made.

One example is: https://anaconda.org/rgrout/conda
