### ISSUE TITLE
Windows build worker deployment and stability (Was issue #150)

### ISSUE THREAD

**Issue by PeterDSteinberg** [Anaconda-Server/anaconda-build#198]
### Improving Windows Deploy and Stability

cc @insertinterestingnamehere @srossross @stephenakearns @pzwang 

This issue has migrated from issue #150 as the causes of the Windows file-locking have been better understood.  

TODO as part of this issue:
 * [x] Update windows deploy docs to have the Admin Miniconda install and the binstar-user specific Miniconda install, where anaconda-build and related stack are installed in the Admin Miniconda at `C:\Miniconda`.
 * [x] Update the Windows deploy docs to also include `conda install python=2.7.10` as a final step in configuration of the two Miniconda environments.  This is likely to avoid file locking conflicts on 2.7 builds where Python 2.7.11 is typically automatically chosen for builds.  We may have had the file locking issue in described in #150 for quite a while, but had gotten away with it because our Windows build workers were often a little out of date on Python minor versions.
 * [x] Research further what is part of the `anaconda-nb-extensions\nb_conda` tests.  cc @bollwyvl .  When the Windows build workers went down in the last few days, both the 32-bit and 64-bit workers crashed at the same time on this specific build, leaving some zombies and 'python has stopped working' popup messages.  These workers were running anaconda-build 0.13.2, so they did not have the code in them for the new process groups-based killing of processes (post-0.13.2 PR merge).  These Windows build workers in production do not have the two installations of Miniconda described in the items above.  My opinion is that for production deploy this week, we should not update the production windows workers, but rather start a new 32- and 64-bit machine from the AMIs Troy has prepared with visual studio, git, etc.

### For context, here is how the build worker deploy instructions need to be updated:

I started an EC2 win-64 instance from the `binstar-build-win-64-1.0.0-ec2(ami-b2f4a0da)` image.  That machine already had git, visual studio tools, and 2 miniconda installs: binstar user's python at `C:\Users\binstar\Miniconda` and Adminstrator's python at `C:\Miniconda`.

Installed `chalmers`, `anaconda-client` develop branches as Admin into the C:\Miniconda environment.  Installed also [anaconda-build PR 197](https://github.com/Anaconda-Server/anaconda-build/pull/197) into the Admin python.

Ran the following commands as the binstar user, then *again* as the Admin user:
```
conda config --set always_yes true
conda update conda
conda install pip
conda install -c https://conda.anaconda.org/tpowell unxutils
conda install conda-build
conda install pywin32 psutil mock patch
conda install python=2.7.10
```

We should see at this point that when logged in as binstar user, the C:\Users\binstar\Miniconda is on the PATH and when logged in as admin C:\Miniconda is on the PATH.

As the Admin user in a cmd session, set some env variables useful for worker data:
```
set HOME_DIR=C:\Users\binstar
set WORKER_ID="win-64-psteinberg-aws-4"
set TOKEN_FILE=%HOME_DIR%\.anaconda.token
set QUEUE=psteinberg/abc
```
Then do these commands, which may require pasting one by one to avoid user input errors on passwords.  These register a worker and only need to be done once in the event of worker restarts:
```
anaconda auth --create -n "anaconda-build-win-64-psteinberg-99o" --scopes "api:build-worker api:read api:build" --out %TOKEN_FILE%
python -c "import socket;print socket.gethostname()" > %HOME_DIR%\HOSTNAME.txt

set /p HOSTNAME=<%HOME_DIR%\HOSTNAME.txt
anaconda login
anaconda worker register -p win-64 --dist aws-win64 --hostname %HOSTNAME%  %QUEUE% --name %WORKER_ID%
anaconda logout
```

Now, as binstar user in a session, redefine the env variables:
```
```
Then use those env vars to use the correct python and chalmers to run the builds.  Note that as the binstar user, `chalmers` as a CLI item is not defined, and that's probably good.
```
set APY=C:\Miniconda\python.exe
set AA=C:\Miniconda\Scripts\anaconda-script.py
set AC=C:\Miniconda\Scripts\chalmers-script.py
%APY% %AC% stop --all --force
%APY% %AC%  remove --all
%APY% %AC%  add --name worker -c "%APY% %AA% --show -t %TOKEN_FILE% worker run %WORKER_ID% --show-new-procs --status-file %HOME_DIR%\worker\worker.status"
%APY% %AC%  start --all
```

### Follow up comments
 * Note I had to downgrade python on both binstar and Admin to 2.7.10 (instead of 2.7.11)
 * The build worker still encounters broken build initialization if a build explicitly requests a Python 2.7.10 install (files lock issue conflicting with the build worker on write of Python 2.7.10 DLLs) or if the binstar and Admin Python are upgraded to 2.7.11, the default minor version of most Python 2.7 builds (files lock issue on Python 2.7.11 DLLs).
 * The PR #189 if installed into this 2-Python setup and run with the commands above, results in failure to start the worker for hitting the runtime check (There were two other `C:\Miniconda\python.exe` processes running at startup [with no further info]), unless the `--ignore-process-check` flag is not given.

**Comment by insertinterestingnamehere** [comment]
Why is it that we aren't seeing similar file locking on Unix based systems? Updating a shared object that is in-use should be disallowed on all operating systems. Is there some fundamental difference in how we set up the processes?

**Comment by PeterDSteinberg** [comment]
@insertinterestingnamehere I'm not sure why we don't see this file locking issue on Unix based systems - I think I was told it was a Windows specific thing.  I haven't found much info about in searches, nor do I have the background in Windows to really comment.

**Comment by insertinterestingnamehere** [comment]
Okay, I just did a little more reading. What's probably going on is the Linux kernel is holding on to a version of the old file until the process using it is terminated. See http://unix.stackexchange.com/a/188041. I didn't think it would do that.

**Comment by PeterDSteinberg** [comment]
Even with the modified windows deployment set up described in the comments of this PR (and now the company deploy wiki as well), we still encounter some file permissions errors, similar to that shown in #150, and can see this outside the CI system, in `conda build` alone.  This issue is now being tracked [here at the conda issues](https://github.com/conda/conda/issues/2079)
