### ISSUE TITLE
double entry for a build

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Server/anaconda-build#212]
This is weird: are there two 12-0 builds or two 13-0 builds? Hard to tell.  And why is 13 marked as failed?

https://anaconda.org/anaconda-nb-extensions/nb_anaconda_theme/builds

Whatever happened here seems to me it is pointing to some serious weirdness that should be understood and fixed.

**Comment by ijstokes** [comment]
This issue also raises the question of how to do better layout to make it more clear which builds are grouped: https://github.com/Anaconda-Server/anaconda-server/issues/1712

**Comment by PeterDSteinberg** [comment]
@dsludwig Do you have any idea how the situation that @ijstokes links to above could arise (two apparent build 0's in build 12)?  I have added this to next milestone unsure of where to start.

**Comment by dsludwig** [comment]
There are two sub-builds with 13.0 with different worker ids:

```
In [19]: b['items'][0].to_dict()
Out[19]:
{'_ipython_display_': {},
 u'build_no': u'13.0',
 u'engine': u'python=2.7',
 u'env': None,
 u'failed': False,
 u'finished': True,
 u'finished_at': datetime.datetime(2016, 2, 18, 15, 51, 54, 546000, tzinfo=<bson.tz_util.FixedOffset object at 0x7f6a223e4650>),
 u'worker_info': {u'dist': u'centos',
  u'hostname': u'anaconda-build-linux-32-2',
  u'worker_id': ObjectId('56bd1798266fe40a43eadeb9')}}

In [20]: b['items'][-1].to_dict()
Out[20]:
{'_ipython_display_': {},
 u'build_no': u'13.0',
 u'engine': u'python=2.7',
 u'env': None,
 u'finished': False,
 u'instructions': {u'build_no': u'13.0',
  u'engine': u'python=2.7',
  u'env': None,
  u'failed': True,
  u'finished': True,
  u'finished_at': datetime.datetime(2016, 2, 11, 22, 7, 2, 792000, tzinfo=<bson.tz_util.FixedOffset object at 0x7f6a223e4650>),
  u'status': u'failure',
  u'sub_build_no': 0,
  u'worker_info': {u'dist': u'aws-linux',
   u'queue_name': u'build-binstar-continuum',
   u'worker_id': ObjectId('56671841ea546b0bbf9cc7ed')}},
 u'platform': u'linux-32',
 u'status': u'added',
 u'sub_build_no': 0}
```

This is probably a race in fetching build jobs from the queue.

**Comment by PeterDSteinberg** [comment]
That explanation makes sense to me.  Is it best to control this situation from the server-side, by simply discarding one of them?  It seems impossible to control completely while there are multiple workers on same queue...

**Comment by dsludwig** [comment]
This is fixed in develop. Note: the existing duplicate build will not be deleted.
