### ISSUE TITLE
`anaconda worker run` cannot run registered worker

### ISSUE THREAD

**Issue by dsludwig** [Anaconda-Server/anaconda-build#222]
If a worker is registered with `--hostname`, there is no way to execute that worker, since the available workers are filtered by the actual hostname of the machine.

Worker names should be unique, so `anaconda worker run <name>` is unambiguous.

hostname should not be filtered, and a warning printed when running on a different hostname/platform.

**Comment by PeterDSteinberg** [comment]
Unique names sound like a good fix.  I'll do that.
