### ISSUE TITLE
quiet: True has issues on Windows

### ISSUE THREAD

**Issue by dsludwig** [Anaconda-Server/anaconda-build#224]
It filters out things that it shouldn't - line endings are `\r\n`.

**Comment by PeterDSteinberg** [comment]
@dsludwig Do you mean that it is removing lines with `\r\n` when it should only be removing those ending with `\r`?

**Comment by dsludwig** [comment]
That's right. There's a number of issues with output right now - I am working on these issues in #216

**Comment by dsludwig** [comment]
Closed by #236
