### ISSUE TITLE
Fix links in build notification email

### ISSUE THREAD

**Issue by PeterDSteinberg** [Anaconda-Server/anaconda-build#228]
I was sent a notification via SES regarding a build with 11 sub-builds.  The links to each build in the email have this form:

```
http://anaconda.org/conda-team/conda-recipes/builds/103.11
```

When resolving it, the `103.11` ends up converting to 103/1 not 103/11 as expected, so the link to build 11 actually takes you to build 1.

**Comment by dsludwig** [comment]
This is fixed on develop.
