### ISSUE TITLE
patch is missing in docker linux-64 image

### ISSUE THREAD

**Issue by cehbrecht** [Anaconda-Server/anaconda-build#24]
some of my recipes use the patch mechanism in the conda build. For this patch needs to be installed:

yum install -y patch

Maybe you would like to add it to the dockerfile ...

**Comment by srossross** [comment]
I will add that and post back here when it is online.

**Comment by danielballan** [comment]
I also encountered this issue. Patch is still missing.

**Comment by srossross** [comment]
I added patch, sorry this issue got side buried.  patch will be included the next build box update.

**Comment by stephenakearns** [comment]
@srossross - based on your comments, I'm assuming this ready to be validated as soon as we are unblocked on Conda/Conda#1861. I'm moving to the "validate" pipeline. Please update if that's not the case.

**Comment by srossross** [comment]
Patch is now installed on the workers. You can now directly submit build worker improvements here: https://github.com/Anaconda-Server/anaconda-build/blob/develop/docker/linux-64/Dockerfile#L5

**Comment by zeehio** [comment]
@srossross I still get the `Did not find 'patch' in: /opt/miniconda/envs/_build/bin:/opt/miniconda/bin:/home/anaconda/env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin` issue in the anaconda.org worker [ip-172-31-14-34-docker-0](https://anaconda.org/zeehio/scikit-umfpack/builds/6/0#L2887).

Is this expected? Am I missing something? Thanks for your time

**Comment by jlaura** [comment]
@srossross @zeehlo :+1:  Also not seeing an identical error.
