### ISSUE TITLE
bug in binstar-build tail logging output

### ISSUE THREAD

**Issue by tswicegood** [Anaconda-Server/anaconda-build#27]
https://gist.github.com/tswicegood/cfbc0bbb2b20ffe9bd9d

Not sure what this is, but appears the messages need to be chunked up before getting sent over the wire.

**Comment by dougalsutherland** [comment]
FYI, I'm still getting this.

```
Traceback (most recent call last):
  File "/usr/local/anaconda/lib/python2.7/logging/handlers.py", line 862, in emit
    self.socket.send(msg)
error: [Errno 40] Message too long
Logged from file info.py, line 46
```

interspersed occasionally with my build output.

**Comment by dougalsutherland** [comment]
Actually, this seems to be the same as #22.

**Comment by srossross** [comment]
This is fixed in the latest release.
