### ISSUE TITLE
Code does not handle mixed-slash paths on Windows

### ISSUE THREAD

**Issue by pzwang** [Anaconda-Server/anaconda-build#30]
In https://github.com/Binstar/binstar-build/blob/master/binstar_build_client/utils/__init__.py#L7, the code should be changed to call `os.path.split()`.

I looked elsewhere in the codebase and found no other uses of `pathsep` so I think this is the only instance of this particular problem.

This problem led to a build failure here: https://binstar.org/javascript/mocha/builds/1/4.  In case that build is removed, the log traceback is pasted below:

    1Build 1.4 Sumitted id:54d946405e7683344fda70a9
    2This build is in the build queue "build-binstar-continuum"...
    3Building on worker WIN-6KBD8SQ4HHD (platform win-64)
    4Starting build javascript/mocha#1.4
    5Build Error: An unhandled exception occurred in the build worker---
    6Traceback (most recent call last):
    7  File "C:\Miniconda\lib\site-packages\binstar_build_client\worker\worker.py", line 185, in build
    8    conda_build_dir=self.args.conda_build_dir)
    9  File "C:\Miniconda\lib\site-packages\binstar_build_client\worker\utils\script_generator.py", line 178, in gen_build_script
    10    exports = create_exports(build_data)
    11  File "C:\Miniconda\lib\site-packages\binstar_build_client\worker\utils\script_generator.py", line 113, in create_exports
    12    conda_root_prefix = get_conda_root_prefix()
    13  File "C:\Miniconda\lib\site-packages\binstar_build_client\utils\__init__.py", line 8, in get_conda_root_prefix
    14    if conda_ext in os.listdir(entry):
    15WindowsError: [Error 3] The system cannot find the path specified: 'C:\\Users\\binstar\\conda-build-miniconda\\Scripts/*.*'

**Comment by tswicegood** [comment]
How could this mixed slash path get generated? It's a good idea to use `os.path.split` to be sure, but I'm more worried that there's code dealing with a path that doesn't use `os.path.join`.

**Comment by srossross** [comment]
@pzwang, @tswicegood, In the code `os.pathsep` is a `:` on posix and a `;` on win32. This is to split the directory components of a `PATH` environment variable. `os.path.split` will split the directory components of a path, which it not the intent of the code here.

I think the solution is to add `os.path.isdir(entry)` above `if conda_ext in os.listdir(entry):`

**Comment by pzwang** [comment]
You're right, I misread the intent of the code and the traceback.  Agreed @Sean, `isdir()` is the right thing, but the next question then is how the glob made it into this part of the code?

**Comment by tswicegood** [comment]
See [my comments][1] in #29.  I'm not sure why that custom code is even in place.  That's the job of conda.  It used to be doable by parsing the data out of `conda info`, but I've since added an option that outputs just the root directory.

[1]: https://github.com/Binstar/binstar-build/pull/29#issuecomment-73727288

**Comment by srossross** [comment]
> how the glob made it into this part of the code

I think that the glob is a part of the win32 `PATH` variable. eg `PATH=C:\Users\binstar\conda-build-miniconda\Scripts/*.*;`

**Comment by tswicegood** [comment]
@srossross if that's the case, how did `PATH` end up with `/*.*;` appended to the end of it?

**Comment by srossross** [comment]
To me, it looks like that happened outside of the binstar-build script.

**Comment by tswicegood** [comment]
That seems odd, but looking through the code I don't see a place where it appears to modify the path.  What runs that code?

**Comment by srossross** [comment]
Is was fixed with #31
