### ISSUE TITLE
Leaving garbage in the system when submission fails

### ISSUE THREAD

**Issue by srossross** [Anaconda-Server/anaconda-build#45]
_From @mutirri on June 10, 2015 14:31_

If recipe crashes for any reason (it doesn't matter what cause that) then not everything is properly cleaned. The great example is running `phantomjs` for testing purposes.
I had to free some resources by killing a lot of hanging processes (63 some time ago, 48 of them one week ago and 11 today).

One possible solution for Linux - to be sure if we clean up all stuff properly - might be `cgroups` framework. However this approach can't be used for Windows and probably it is not available for MacOSX also.

_Copied from original issue: Anaconda-Server/binstar-build-worker#14_

**Comment by dsludwig** [comment]
@srossross is this handled by #158 ?

**Comment by PeterDSteinberg** [comment]
@dsludwig  There is still a windows process / zombie clean up issue, e.g. https://github.com/Anaconda-Server/anaconda-build/issues/176

**Comment by srossross** [comment]
@PeterDSteinberg are you sure this is related to #176?

**Comment by srossross** [comment]
I think this **is** solved by #158. re-open if I am wrong. Peter I logged our issue with conda. conda/conda#1961
