### ISSUE TITLE
Add conda-server-build to anaconda channel

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Server/anaconda-build#64]
Now that `binstar` is being replaced by `conda-server`, it makes sense that `binstar-build` be replaced by `conda-server-build`. However, this does not yet exist in the anaconda channel. Can this please be added?

Also, this line needs to be changed ( https://github.com/Anaconda-Server/conda-server-build/blob/develop/conda.recipe/conda.yaml#L19 ).

**Comment by malev** [comment]
@jakirkham we are in the process to rename binstar-build into conda-server-build. Thanks

**Comment by jakirkham** [comment]
Of course, I just ran into this transition today so was trying to take stock of where everything was.

**Comment by jakirkham** [comment]
Partially help for this issue here ( https://github.com/Anaconda-Server/conda-server-build/pull/65 ).

**Comment by jakirkham** [comment]
Looks like this is going to get renamed again.

**Comment by srossross** [comment]
This is now released as `anaconda-build` in the default conda channels.
