### ISSUE TITLE
anaconda-build cannot download long messages

### ISSUE THREAD

**Issue by izaid** [Anaconda-Server/anaconda-build#70]
Using my dynd-python package as an example, "anaconda-build tail dynd/dynd-python 25". This gives me a number of errors like:

Traceback (most recent call last):
  File "/home/irwin/miniconda/lib/python2.7/logging/handlers.py", line 862, in emit
    self.socket.send(msg)
error: [Errno 90] Message too long
Logged from file info.py, line 37

**Comment by PeterDSteinberg** [comment]
This issue I have seen as well intermittently and it relates to the style of threaded logging done before the gevent change just recently and that logging's interaction with p0.stdout.close().  If we don't observe this bug for a while after the gevent logging merge, we should close this issue.

**Comment by srossross** [comment]
This is fixed in the latest release. please re-open if you see it again.
