### ISSUE TITLE
Build logs are truncated either on anaconda.org or through the command line

### ISSUE THREAD

**Issue by izaid** [Anaconda-Server/anaconda-build#71]
This has been an issue for me since August 7. Basically, I can no longer see the entire build log of any package. I don't of any way to get at the build log.

See https://anaconda.org/dynd/libdynd/builds/130/0, for instance.

**Comment by izaid** [comment]
Can I get help with this please?

**Comment by srossross** [comment]
This will be fixed with #118

**Comment by stephenakearns** [comment]
blocked until @ilanschnell releases 0.13.1 release of Anaconda Build. Cc: @csoja

**Comment by ilanschnell** [comment]
Other people on the team, can release a new version of anaconda-build
also.  I'll be back in the office next Wednesday.

**Comment by srossross** [comment]
fixed
