### ISSUE TITLE
Anaconda server cannot find git

### ISSUE THREAD

**Issue by izaid** [Anaconda-Server/anaconda-build#80]
The documentation (http://docs.binstar.org/examples.html) tells me that "binstar build MY_GIT_REPOSITORY" should work. So, when I try "binstar-build submit https://github.com/libdynd/dynd-python" (which is a repository that has a working conda recipe), I get "git: command not found".

https://binstar.org/izaid/dynd-python/builds/6/0

**Comment by izaid** [comment]
This is also an issue when I simply "binstar-build submit ." with a local recipe.

**Comment by mutirri** [comment]
`git command not found` was related to my maintaining tasks on docker images (I didn't recreate shortcut for git in `/usr/local/git/bin`) and your submission was using `build/binstar/public` queue.
Right now it is available:

```
[binstar@63e81eea68fc ~]# git --version
git version 2.0.5
```

And here is output from submitted task:
https://binstar.org/mutirri/dynd-python/builds/7/0
