### ISSUE TITLE
Anaconda Cloud cannot upload packages that build and test successfully

### ISSUE THREAD

**Issue by izaid** [Anaconda-Server/anaconda-build#81]
A package can build and test completely fine, but fail at the upload stage on anaconda.org.

For DyND Python, I was able to make it build and test successfully on Linux 64. But, at the upload stage, the pre-provided command simply fails. Here is an example of that: https://anaconda.org/dynd/dynd-python/builds/86/0. Here is the preceding build which built and tested fine: https://anaconda.org/dynd/dynd-python/builds/85/0

**Comment by stephenakearns** [comment]
Hi @ijstokes - I see your new issue #141 - can you review this issue and let me know if it's a duplicate or a different issue?

**Comment by srossross** [comment]
There is not enough info to reproduce the issue any more. A traceback is needed. reopen if the issue is still affecting the builds.
