### ISSUE TITLE
Build worker should not auto register

### ISSUE THREAD

**Issue by srossross** [Anaconda-Server/anaconda-build#83]
Currently the build worker registers itself, this should not be the case. 

The build worker should no longer require a `-t token` argument and instead take a `worker_id`. The worker id would be generated from a previous step `anaconda build register-worker `.

We need to make sure that the UX still makes sense.

**Comment by stephenakearns** [comment]
Hi Sean - I think this should be moved to the 2.9.4 release milestone. Can you update when you have a moment?
