### ISSUE TITLE
Queues should have an info page at anaconda.org/user/queues/*

### ISSUE THREAD

**Issue by srossross** [Anaconda-Server/anaconda-build#85]

**Comment by stephenakearns** [comment]
Page should contain the following information...
1. Queue name/ID
2. build jobs
3. build history
4. available workers and status (online/offline)
5. log files from the workers (maybe? not sure about this - maybe just
recent activity stream for worker status)

On Wed, Sep 2, 2015 at 1:26 PM, Sean <notifications@github.com> wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Anaconda-Server/anaconda-build/issues/85>.
>



-- 
*Stephen Kearns*
*Product Manager*

**Comment by stephenakearns** [comment]
@goanpeca  please link out to other active issues and then close this duplicate

**Comment by goanpeca** [comment]
This is being tackled in Anaconda Server issues Anaconda-Server/anaconda-server#870 and Anaconda-Server/anaconda-server#871

**Comment by stephenakearns** [comment]
To see an example of this page - go here: https://beta.anaconda.org/binstar/queues/
