### ISSUE TITLE
Build: Test and Update Anaconda Build Documentation via fresh install

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Server/anaconda-build#97]
changes to the SU worker as well as register/deregister and other updates as needed based on testing install/config

**Comment by stephenakearns** [comment]
relates to PR #88

**Comment by stephenakearns** [comment]
Hi @amccarty  - how did this one go? Any updates before the standup today?

**Comment by stephenakearns** [comment]
Hi @amccarty - I think I saw an FD note saying that you added your notes somewhere, but I'm not seeing them here or in the other linked issue. Did you just update the documentation directly? Overall, smooth process with good documentation?

**Comment by amccarty** [comment]
@stephenakearns I worked with @goanpeca and I believe he incorporated my notes into his updates.

**Comment by goanpeca** [comment]
That is correct :-) :+1:

**Comment by stephenakearns** [comment]
Hi @amccarty - checking in to find out the reason for reopening this one?

**Comment by stephenakearns** [comment]
update from @PeterDSteinberg - blocked on #150

**Comment by PeterDSteinberg** [comment]
* Build workers are up and running for all operating systems now. 
* Company wiki on deployment has been updated for a 2-miniconda installation set up on Windows
* [conda issue 2079](https://github.com/conda/conda/issues/2079) was responsible for #150. Moving this issue to 0.14.1 so deployment can be further refined in conjunction with a fix for conda issue 2079 for greater windows stability.

**Comment by PeterDSteinberg** [comment]
I am closing this as complete after the updates to the company wiki on deployment for windows described above.  Those instructions are in use for binstar queues and conda-team.
